import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navigation/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="mt-[92px]">{children}</div>
      </body>
    </html>
  );
}
